export {default as Nav} from "./nav"
export {default as Footer} from "./footer"
export {default as About} from "./About"
export {default as Cart } from "./Cart"
export {default as Unauthorised} from "./Unauthorized"
export {default as Order} from "./Order"
export {default as Orders} from "./Orders"
export {default as Product} from "./Product"
export {default as Products} from "./Products"
export {default as Login} from "./Login"
export {default as Signup} from "./Signup"
export {default as Home} from "./Home"
export {default as AddProduct} from "./AddProduct"


